# Generated by Django 5.2.7 on 2025-11-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AAEnergiesDatuak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('corriente_l1', models.FloatField()),
                ('corriente_l2', models.FloatField()),
                ('corriente_l3', models.FloatField()),
                ('corriente_neutro', models.FloatField()),
                ('p_activa_L1', models.FloatField()),
                ('p_activa_L2', models.FloatField()),
                ('p_activa_L3', models.FloatField()),
                ('cos_Phi_L1', models.FloatField()),
                ('cos_Phi_L2', models.FloatField()),
                ('cos_Phi_L3', models.FloatField()),
                ('frecuencia', models.FloatField()),
                ('p_capacitivia_L1', models.FloatField()),
                ('p_capacitivia_L2', models.FloatField()),
                ('p_capacitivia_L3', models.FloatField()),
                ('p_inductiva_L1', models.FloatField()),
                ('p_inductiva_L2', models.FloatField()),
                ('p_inductiva_L3', models.FloatField()),
                ('tension_l1', models.FloatField()),
                ('tension_l12', models.FloatField()),
                ('tension_l2', models.FloatField()),
                ('tension_l23', models.FloatField()),
                ('tension_l3', models.FloatField()),
                ('tension_l31', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('rol', models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('viewer', 'Viewer')], max_length=20)),
            ],
        ),
    ]
